# Generated by Django 3.1.3 on 2021-01-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210118_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
