# Generated by Django 3.1.3 on 2021-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(verbose_name='Дата рождения (DD.MM.YYYY)'),
        ),
    ]
